version: "3.9"
services:
  coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
      CODER_PROVISIONER_DAEMONS: ${CODER_PROVISIONER_DAEMONS:-3}
      CODER_DOCS_URL: ${CODER_DOCS_URL:-https://coder.com/docs}
      CODER_HTTP_FORWARDED_PROTO: "https"
      CODER_REDIRECT_TO_ACCESS_URL: "true"
    group_add:
      - "${DOCKER_GROUP_ID:-998}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - coder_home:/home/coder
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-coder}
    volumes:
      - coder_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable
    depends_on:
      - coder
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped

volumes:
  coder_data:
    driver: local
    driver_opts:
      type: none
      device: ${CODER_DATA_PATH:-./coder_data}
      o: bind
  coder_home:
    driver: local
    driver_opts:
      type: none
      device: ${CODER_HOME_PATH:-./coder_home}
      o: bind

