version: '3.8'

services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    stdin_open: true
    tty: true
    restart: unless-stopped

